### ISSUE TITLE
希望同roadmap里面一样加入url配置

### ISSUE THREAD

**Issue by iamllitog** [fex-team/fis-packager-map#1]

**Comment by oxUnd** [comment]
啥意思，打包插件不负责设置各项参数啊！

**Comment by iamllitog** [comment]
我的意思是，在roadmap里会有类似这样的设置
{
                //所有image目录下的.png，.gif文件
                reg : /^\/images\/(._.(?:png|gif))/i,
                //访问这些图片的url是 '/m/xxxx?log_id=123'
                url : '/m/$1?log_id=123',
                //发布到/static/pic/xxx目录下
                release : '/static/pic/$1'
}
那么
pack : {
        'pkg/aio.js' : ['__/demo.js', /\/script.js$/i],
        'pkg/aio.css' : '_*.css
}
打包中应该也有类似于url的设置吧。。。这样方便定位，要不然定位的路径始终是pkg/aio.js

注：不好意思我貌似跑到源码中提问了- -

**Comment by oxUnd** [comment]
``` js
fis.config.set('pack', {
  'pkg 源码路径': [
    '子文件源码路径',
    '子文件源码路径'
  ]
});
```

那么既然都是源码路径，假设我配置了；

``` js
fis.config.set('pack', {
  'pkg/aio.js': {
    'a.js',
    'b.js'
  }
});
```

那么我想重定向或者重新定位 pkg 的话，只需要针对它配置 roadmap 即可。

``` js
fis.config.set('roadmap.path', [
   {
     reg: 'pkg**',
     release: '/static/$&'
   }
]);
```

大概就这样

**Comment by iamllitog** [comment]
亲测可行，，3q very much memeda
